hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

_admin_logout:
    pattern: /logout

google_login:
    pattern: /login/check-google

facebook_login:
    pattern: /login/check-facebook

linkedin_login:
    pattern: /login/check-linkedin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_bazinga_jstranslation:
    resource: "@BazingaJsTranslationBundle/Resources/config/routing/routing.yml"

cmf_media_file:
    resource: "@CmfMediaBundle/Resources/config/routing/file.xml"

cmf_media_image:
    resource: "@CmfMediaBundle/Resources/config/routing/image.xml"

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

i_cup_public_site:
    resource: "@ICupPublicSiteBundle/Controller/"
    type:     annotation
    prefix:   /

api:
    resource: "@APIBundle/Controller/"
    type:     annotation
    schemes:  https
    prefix:   /service/api

