security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_CLUB_ADMIN:   ROLE_USER
        ROLE_EDITOR:       ROLE_USER
        ROLE_EDITOR_NEWS:  ROLE_EDITOR
        ROLE_EDITOR_ADMIN: ROLE_EDITOR
        ROLE_ADMIN:        [ROLE_EDITOR_ADMIN, ROLE_EDITOR_NEWS, ROLE_CLUB_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN:  ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
#            id: fos_user.user_manager

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|fonts)/
            security: false

        main:
            pattern:    ^/
            switch_user: true
#            access_denied_url: /foo/error403
#            access_denied_handler: some.service.id
            form_login:
                provider: fos_userbundle
                csrf_provider: security.csrf.token_manager

            logout:       true
            anonymous:    true

            oauth:
                failure_path: /connect
                use_forward: false
                login_path: /login
                check_path: /connect
                provider: fos_userbundle
                resource_owners:
                    facebook: facebook_login
                    google: google_login
#                    linkedin: linkedin_login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
#                    service: app.provider.oauth

    access_control:
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/club, roles: ROLE_CLUB_ADMIN }
        - { path: ^/host, roles: ROLE_EDITOR }
        - { path: ^/edit, roles: ROLE_EDITOR_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/connect, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        #- { path: ^/admin/, role: ROLE_ADMIN }
