parameters:
    tournament_table: "ICup\\Bundle\\PublicSiteBundle\\Entity\\Doctrine\\Tournament"
    club_table: "ICup\\Bundle\\PublicSiteBundle\\Entity\\Doctrine\\Club"
    
services:    
    kernel.listener.exception.listener:
        class: "ICup\\Bundle\\PublicSiteBundle\\EventListener\\ExceptionListener"
        arguments:
            - "@templating"
            - "@router"
            - "@logger"
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    kernel.listener.translation.listener:
        class: ICup\Bundle\PublicSiteBundle\EventListener\TranslatorListener
        arguments:
            - "@translator"
        tags:
            - { name: kernel.event_subscriber }
        
    kernel.listener.locale.listener:
        class: ICup\Bundle\PublicSiteBundle\EventListener\LocaleListener
        arguments:
            - "@twig"
            - "@logger"
            - "%kernel.default_locale%"
        tags:
            - { name: kernel.event_subscriber }
            
    kernel.listener.authentication.listener:
        class: ICup\Bundle\PublicSiteBundle\EventListener\AuthenticationListener
        arguments:
          - "@service_container"
          - "@logger"
        tags:
            - { name: kernel.event_subscriber }

    form.type_extension.field:
        class: "ICup\\Bundle\\PublicSiteBundle\\Form\\Extension\\FieldTypeExtension"
        tags:
          - { name: "form.type_extension", alias: "form" }

    form.type_extension.button:
        class: "ICup\\Bundle\\PublicSiteBundle\\Form\\Extension\\ButtonTypeExtension"
        tags:
          - { name: "form.type_extension", alias: "submit" }

    app.provider.oauth:
        class: ICup\Bundle\PublicSiteBundle\Security\Core\User\OAuthUserProvider
        arguments: [@fos_user.user_manager,{facebook: facebookID, google: googleID}]

# REGISTER TWIG EXTENSIONS
    custom.twig.sandbox.policy:
        class: Twig_Sandbox_SecurityPolicy
        arguments:
          # tags
          - [ if, for, trans, transchoice ]
          # filters
          - [ upper, capitalize, trans, transchoice, join, lower, date, escape, length ]
          # methods
          - { %tournament_table%: [getName, getEdition], %club_table%: [getName] }
          # properties
          - { %tournament_table%: [name, edition], %club_table%: [name] }
          # functions
          - [ cycle, asset ]
        public: false

    custom.twig.extension.sandbox:
        class: Twig_Extension_Sandbox
        arguments:
          - "@custom.twig.sandbox.policy"
        tags:
          - { name: 'twig.extension' }

    custom.twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
          - { name: 'twig.extension' }

    custom.twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
          - { name: 'twig.extension' }

# APPEND NEW TWIG LOADER - DatabaseTwigLoader
    icup.publicsitebundle.twig_filesystem_loader:
        class: "Symfony\\Bundle\\TwigBundle\\Loader\\FilesystemLoader"
        arguments:
            - "@templating.locator"
            - "@templating.name_parser"

    icup.publicsitebundle.twig_database_loader:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\DatabaseTwigLoader"
        arguments:
          - "@entity"
          - "@logger"

    icup.publicsitebundle.twig_chain_loader:
        class: Twig_Loader_Chain
        arguments:
            - [ "@icup.publicsitebundle.twig_filesystem_loader", "@icup.publicsitebundle.twig_database_loader" ]
        tags:
          - { name: 'twig.loader' }

# BUSINESS LOGIC 
    entity:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\Doctrine\\Entity"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "ICup\\Bundle\\PublicSiteBundle\\Entity\\Doctrine\\"
          - "@logger"

    logic:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\Doctrine\\BusinessLogic"
        arguments:
          - "@service_container"
          - "@logger"

    tmnt:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\Doctrine\\TournamentSupport"
        arguments:
          - "@service_container"
          - "@logger"

    match:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\Doctrine\\MatchSupport"
        arguments:
          - "@service_container"
          - "@logger"

    planning:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\MatchPlanning"
        arguments:
          - "@service_container"
          - "@logger"

    util:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\Util"
        arguments:
          - "@service_container"
          - "@logger"

    orderTeams:
        class: "ICup\\Bundle\\PublicSiteBundle\\Services\\OrderTeams"
        arguments:
          - "@service_container"
          - "@logger"

    test:
        class: "ICup\\Bundle\\PublicSiteBundle\\Tests\\Services\\TestSupport"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "ICup\\Bundle\\PublicSiteBundle\\Entity\\Doctrine\\"
          - "@logger"

