<?php

namespace ICup\Bundle\PublicSiteBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class TournamentController__JMSInjector
{
    public static function inject($container) {
        $instance = new \ICup\Bundle\PublicSiteBundle\Controller\TournamentController();
        return $instance;
    }
}
